name: shift
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - python=3.10.18
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - backoff==2.2.1
      - cachecontrol==0.14.3
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cryptography==46.0.3
      - distro==1.9.0
      - dnspython==2.8.0
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.119.1
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.3.1
      - firebase-admin==7.1.0
      - google-api-core==2.26.0
      - google-auth==2.41.1
      - google-cloud-core==2.4.3
      - google-cloud-firestore==2.21.0
      - google-cloud-storage==3.4.1
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - langfuse==3.8.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - msgpack==1.1.2
      - openai==2.6.1
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-http==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - packaging==25.0
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pyjwt==2.10.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rsa==4.9.1
      - sentry-sdk==2.42.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.48.0
      - tqdm==4.67.1
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - wrapt==1.17.3
      - zipp==3.23.0
prefix: /Users/paul/miniconda3/envs/shift
